{"url": "https://api.github.com/repos/rust-lang/rust/issues/33812", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/33812/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/33812/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/33812/events", "html_url": "https://github.com/rust-lang/rust/issues/33812", "id": 156273619, "node_id": "MDU6SXNzdWUxNTYyNzM2MTk=", "number": 33812, "title": "Behavior on uncaught exception is different between -C panic=abort and -C panic=unwind", "user": {"login": "tomaka", "id": 1412254, "node_id": "MDQ6VXNlcjE0MTIyNTQ=", "avatar_url": "https://avatars.githubusercontent.com/u/1412254?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tomaka", "html_url": "https://github.com/tomaka", "followers_url": "https://api.github.com/users/tomaka/followers", "following_url": "https://api.github.com/users/tomaka/following{/other_user}", "gists_url": "https://api.github.com/users/tomaka/gists{/gist_id}", "starred_url": "https://api.github.com/users/tomaka/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tomaka/subscriptions", "organizations_url": "https://api.github.com/users/tomaka/orgs", "repos_url": "https://api.github.com/users/tomaka/repos", "events_url": "https://api.github.com/users/tomaka/events{/privacy}", "received_events_url": "https://api.github.com/users/tomaka/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2016-05-23T12:53:28Z", "updated_at": "2016-06-27T16:28:45Z", "closed_at": "2016-06-27T16:16:13Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "When a program compiled with `-C panic=abort` panicks, the stack trace is printed and an illegal instruction is triggered (with the `ud2` opcode).\nWhen a program compiled with `-C panic=unwind` doesn't catch a panic in the main thread, the stack trace is printed and the program aborts.\n\nI don't have any strong opinion in favor of triggering an illegal instruction vs aborting, but I think the behavior should be the same between `panic=abort` and `panic=unwind`.\n", "closed_by": {"login": "alexcrichton", "id": 64996, "node_id": "MDQ6VXNlcjY0OTk2", "avatar_url": "https://avatars.githubusercontent.com/u/64996?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alexcrichton", "html_url": "https://github.com/alexcrichton", "followers_url": "https://api.github.com/users/alexcrichton/followers", "following_url": "https://api.github.com/users/alexcrichton/following{/other_user}", "gists_url": "https://api.github.com/users/alexcrichton/gists{/gist_id}", "starred_url": "https://api.github.com/users/alexcrichton/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alexcrichton/subscriptions", "organizations_url": "https://api.github.com/users/alexcrichton/orgs", "repos_url": "https://api.github.com/users/alexcrichton/repos", "events_url": "https://api.github.com/users/alexcrichton/events{/privacy}", "received_events_url": "https://api.github.com/users/alexcrichton/received_events", "type": "User", "site_admin": false}, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/33812/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/33812/timeline", "performed_via_github_app": null, "state_reason": "completed"}