{"url": "https://api.github.com/repos/rust-lang/rust/issues/55237", "repository_url": "https://api.github.com/repos/rust-lang/rust", "labels_url": "https://api.github.com/repos/rust-lang/rust/issues/55237/labels{/name}", "comments_url": "https://api.github.com/repos/rust-lang/rust/issues/55237/comments", "events_url": "https://api.github.com/repos/rust-lang/rust/issues/55237/events", "html_url": "https://github.com/rust-lang/rust/issues/55237", "id": 372269086, "node_id": "MDU6SXNzdWUzNzIyNjkwODY=", "number": 55237, "title": "Unable to trace an crash from the backtrace, no trace for my own code", "user": {"login": "luyang177", "id": 2854721, "node_id": "MDQ6VXNlcjI4NTQ3MjE=", "avatar_url": "https://avatars.githubusercontent.com/u/2854721?v=4", "gravatar_id": "", "url": "https://api.github.com/users/luyang177", "html_url": "https://github.com/luyang177", "followers_url": "https://api.github.com/users/luyang177/followers", "following_url": "https://api.github.com/users/luyang177/following{/other_user}", "gists_url": "https://api.github.com/users/luyang177/gists{/gist_id}", "starred_url": "https://api.github.com/users/luyang177/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/luyang177/subscriptions", "organizations_url": "https://api.github.com/users/luyang177/orgs", "repos_url": "https://api.github.com/users/luyang177/repos", "events_url": "https://api.github.com/users/luyang177/events{/privacy}", "received_events_url": "https://api.github.com/users/luyang177/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 211668062, "node_id": "MDU6TGFiZWwyMTE2NjgwNjI=", "url": "https://api.github.com/repos/rust-lang/rust/labels/T-libs-api", "name": "T-libs-api", "color": "bfd4f2", "default": false, "description": "Relevant to the library API team, which will review and decide on the PR/issue."}, {"id": 266005765, "node_id": "MDU6TGFiZWwyNjYwMDU3NjU=", "url": "https://api.github.com/repos/rust-lang/rust/labels/O-windows-msvc", "name": "O-windows-msvc", "color": "6e6ec0", "default": false, "description": "Toolchain: MSVC, Operating system: Windows"}], "state": "open", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-10-21T01:29:49Z", "updated_at": "2019-01-27T21:25:38Z", "closed_at": null, "author_association": "NONE", "active_lock_reason": null, "body": "Windows, use msvc toolchain, release build and config \u2018debug = true\u2019 in [profile.release], and marked #[inline(never)]\r\nthe problem is unable to trace an crash from the backtrace, no trace for my own code.\r\nwhile debug build backtrace works, can find my own code line\r\n\r\n```\r\nrustc 1.29.1 (b801ae664 2018-09-20)\r\ncargo 1.29.0 (524a578d7 2018-08-05)\r\n\r\nthe trace is below:\r\n\r\nPS D:\\rust-projects\\hello_cargo\\target\\release> $env:RUST_BACKTRACE=1\r\nPS D:\\rust-projects\\hello_cargo\\target\\release> .\\hello_cargo.exe\r\nThe value of x is: 5\r\nthread \u2018main\u2019 panicked at \u2018Not a number!: ParseIntError { kind: InvalidDigit }\u2019, libcore\\result.rs:945:5\r\nstack backtrace:\r\n0: std::sys::windows::backtrace::set_frames\r\nat C:\\projects\\rust\\src\\libstd\\sys\\windows\\backtrace\\mod.rs:104\r\n1: std::sys::windows::backtrace::set_frames\r\nat C:\\projects\\rust\\src\\libstd\\sys\\windows\\backtrace\\mod.rs:104\r\n2: std::sys_common::backtrace::_print\r\nat C:\\projects\\rust\\src\\libstd\\sys_common\\backtrace.rs:71\r\n3: std::sys_common::backtrace::_print\r\nat C:\\projects\\rust\\src\\libstd\\sys_common\\backtrace.rs:71\r\n4: std::panicking::default_hook::{{closure}}\r\nat C:\\projects\\rust\\src\\libstd\\panicking.rs:211\r\n5: std::panicking::default_hook\r\nat C:\\projects\\rust\\src\\libstd\\panicking.rs:227\r\n6: std::panicking::rust_panic_with_hook\r\nat C:\\projects\\rust\\src\\libstd\\panicking.rs:475\r\n7: std::panicking::continue_panic_fmt\r\nat C:\\projects\\rust\\src\\libstd\\panicking.rs:390\r\n8: std::panicking::rust_begin_panic\r\nat C:\\projects\\rust\\src\\libstd\\panicking.rs:325\r\n9: core::panicking::panic_fmt\r\nat C:\\projects\\rust\\src\\libcore\\panicking.rs:77\r\n10: core::result::unwrap_failedcore::num::ParseIntError\r\nat C:\\projects\\rust\\src\\libcore\\macros.rs:26\r\n11: core::result::Result<u32, core::num::ParseIntError>::expect\r\nat C:\\projects\\rust\\src\\libcore\\result.rs:809\r\n12: core::result::Result<u32, core::num::ParseIntError>::expect\r\nat C:\\projects\\rust\\src\\libcore\\result.rs:809\r\n13: std::rt::lang_start::{{closure}}<()>\r\nat C:\\projects\\rust\\src\\libstd\\rt.rs:74\r\n14: std::rt::lang_start_internal::{{closure}}\r\nat C:\\projects\\rust\\src\\libstd\\rt.rs:59\r\n15: std::rt::lang_start_internal::{{closure}}\r\nat C:\\projects\\rust\\src\\libstd\\rt.rs:59\r\n16: panic_unwind::__rust_maybe_catch_panic\r\nat C:\\projects\\rust\\src\\libpanic_unwind\\lib.rs:105\r\n17: std::panicking::try\r\nat C:\\projects\\rust\\src\\libstd\\panicking.rs:289\r\n18: std::panicking::try\r\nat C:\\projects\\rust\\src\\libstd\\panicking.rs:289\r\n19: std::panicking::try\r\nat C:\\projects\\rust\\src\\libstd\\panicking.rs:289\r\n20: main\r\n21: invoke_main\r\nat f:\\dd\\vctools\\crt\\vcstartup\\src\\startup\\exe_common.inl:78\r\n22: invoke_main\r\nat f:\\dd\\vctools\\crt\\vcstartup\\src\\startup\\exe_common.inl:78\r\n23: BaseThreadInitThunk\r\n24: RtlUserThreadStart\r\n```", "closed_by": null, "reactions": {"url": "https://api.github.com/repos/rust-lang/rust/issues/55237/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/rust-lang/rust/issues/55237/timeline", "performed_via_github_app": null, "state_reason": null}